# ダミー変数

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('sample_data3.csv')
pd.get_dummies(df, drop_first=True)

,space,rent,age,facing_direction_North,facing_direction_South,facing_direction_West
0,20,13.958824,3,0,1,0
1,25,11.533805,13,0,1,0
2,28,14.269547,18,1,0,0
3,30,18.722680,10,0,0,1
4,36,19.602674,6,0,0,1
5,51,16.068166,1,0,1,0
6,55,23.183599,5,0,0,0
7,62,22.212595,2,1,0,0
8,83,29.357010,5,1,0,0
9,103,37.565129,23,0,0,1

,space,rent,age,facing_direction_North,facing_direction_South,facing_direction_West
0,20,13.958824,3,0,1,0
1,25,11.533805,13,0,1,0
2,28,14.269547,18,1,0,0
3,30,18.722680,10,0,0,1
4,36,19.602674,6,0,0,1
5,51,16.068166,1,0,1,0
6,55,23.183599,5,0,0,0
7,62,22.212595,2,1,0,0
8,83,29.357010,5,1,0,0
9,103,37.565129,23,0,0,1